# Generated by Django 5.0.6 on 2024-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feadev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default='Clique para acessar o projeto', max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(default='Titulo Default', max_length=100),
            preserve_default=False,
        ),
    ]
