# Generated by Django 5.0.6 on 2024-09-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feadev', '0002_projeto_descricao_projeto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='feadev.grupo'),
        ),
    ]
