# Generated by Django 5.0.6 on 2024-09-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feadev', '0005_alter_user_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='situacao',
            field=models.BooleanField(),
        ),
    ]
